import Input from './specs/component/Input';
import Button from './specs/component/Button';
import Dialog from './specs/component/Dialog';
import InputDialog from './specs/component/InputDialog';
import Tabs from './specs/component/Tabs';
import SVGRenderer from './specs/component/SVGRenderer';
import AddTab from './specs/subject/AddTab';
import RemoveTab from './specs/subject/RemoveTab';
import RenameTab from './specs/subject/RenameTab';