import Input from './specs/Input';
import Button from './specs/Button';
import Dialog from './specs/Dialog';
import InputDialog from './specs/InputDialog';
import Tabs from './specs/Tabs';
import SVGRenderer from './specs/SVGRenderer';
import AddTab from './specs/subject/AddTab';
import RemoveTab from './specs/subject/RemoveTab';
import RenameTab from './specs/subject/RenameTab';